# Generated by Django 2.2.3 on 2019-07-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_merge_20180115_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
